### ISSUE TITLE
can not find lib pytib

### ISSUE THREAD

**Issue by OptimusV5** [Esukhia/dakje-desktop#2]
when i try : pip install pytib
i got : 
Could not find a version that satisfies the requirement pytib (from versions: )
No matching distribution found for pytib

**Comment by drupchen** [comment]
It is normal since pytib is not published in pypi.
By the way, the development of tibetaneditor has moved since a long time to https://github.com/nuwainfo/tibetaneditor

As for pytib itself, it has been dropped and now [pybo](https://github.com/Esukhia/pybo) replaces it fully while being much more effecient and flexible. 

You can do `pip install pybo` (or `pip3 install pybo` if it doesn't work)
I am eager to hear from you on the pybo repo!
